### ISSUE TITLE
Distinguish from regular GZDoom

### ISSUE THREAD

**Issue by alexey-lysiuk** [drdteam/gzdoom-gles#4]
In my opinion, it would be great to distinguish GLES version from regular GZDoom. This includes names of project in CMake, executable, config, main .pk3 file, etc. Custom icon will be nice to have too.

Thoughts? Ideas? Concerns?

**Comment by madame-rachelle** [comment]
The goal of this project is to eventually get merged into GZDoom proper. I have been trying to set things up on this end so that it can actually happen - if it ever does. However, while it is still its own separate thing, a new name probably wouldn't be a bad idea, but I am not the greatest at coming up with names.

That being said I just asked Emile about doing the same thing with Raze since he said he was working on that, too.

I think ultimately it comes down to how @coelckers feels about this. I'm also going to ping @Tormentor667 since he is the one who did the logos, so he should probably be in this discussion, as well.

**Comment by alexey-lysiuk** [comment]
GZDoom-GLES is fine, I think. The idea is just to avoid confusion with GZDoom.

**Comment by Tormentor667** [comment]
I can take care of a fitting logo if you need me. Just drop me a line to info@realm667.com as soon as decisions have been made :)

**Comment by madame-rachelle** [comment]
This is redundant since the branch was merged.
